### ISSUE TITLE
Strickle button appears before interactive component has been completed

### ISSUE THREAD

**Issue by tomgreenfield** [cgkineo/adapt-strickle#5]

**Comment by tomgreenfield** [comment]
For reference: https://dev.kineo.com/trac/ken13183/ticket/1#comment:7.

**Comment by oliverfoster** [comment]
if the _strickle object is inside a component and not a seperate component, a quick fix is to use the _lock: [ "component_id" ] fix. where by:

**Comment by oliverfoster** [comment]
removed in previous rewrite.
