### ISSUE TITLE
Button appears when feedback is shown for previous question

### ISSUE THREAD

**Issue by tomgreenfield** [cgkineo/adapt-strickle#8]
From https://dev.kineo.com/trac/ken13133/ticket/14:

>If I unlock 2 or more MCQ components, I can confused the trickle functionality by opening the  PREVIOUS MCQ's feedback popup, which makes the trickle think the CURRENT MCQ is done.

>However, the 'fake' trickle ('Next question' bar) once selected does not work, so it's not truly unlocking  anything. Odd.

**Comment by oliverfoster** [comment]
#9 closed
